create table WALLET_ACCOUNT
(
    ID       number primary key,
    CURRENCY varchar2(3)  not null,
    STATUS   varchar2(20) not null check (STATUS in ('ACTIVE','FROZEN','CLOSED')),
    BALANCE  number       not null
);

create table account
(
    id        number generated by default as identity primary key,
    fName     varchar2(50)  not null,
    lName     varchar2(50)  not null,
    email     varchar2(200) not null unique,
    password  varchar2(100) not null,
    wallet_id number references wallet_account (id)
);

create table WALLET_JOURNAL
(
    ENTRY_ID    number generated by default as identity primary key,
    REQUEST_ID  varchar2(64) not null,
    TS_CREATED  timestamp with time zone default systimestamp not null,
    POSTING_SEQ number        not null check (POSTING_SEQ in (1, 2)),
    ACCOUNT_ID  number        not null references WALLET_ACCOUNT (ID),
    CURRENCY    varchar2(3)   not null,
    AMOUNT      number        not null check (AMOUNT > 0),
    SIDE        varchar2(6)   not null check (SIDE in ('DEBIT','CREDIT')),
    DESCRIPTION varchar2(200),
    constraint uq_journal_request unique (REQUEST_ID, POSTING_SEQ)
);

create index ix_journal_account_ts on WALLET_JOURNAL (ACCOUNT_ID, TS_CREATED);

create or replace view WALLET_BALANCE_V as
select a.id,
       a.currency,
       coalesce(sum(case when j.side = 'CREDIT' then j.amount else -j.amount end), 0) as ledger_balance,
       a.balance                                                                      as materialized_balance
from WALLET_ACCOUNT a
         left join WALLET_JOURNAL j on j.account_id = a.id and j.currency = a.currency
group by a.id, a.currency, a.balance;
