CREATE TABLE account
(
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fName     VARCHAR2(50)  NOT NULL,
    lName     VARCHAR2(50)  NOT NULL,
    email     VARCHAR2(200) NOT NULL UNIQUE,
    password  VARCHAR2(100) NOT NULL,
    wallet_id NUMBER REFERENCES wallet_account (id)
);